version: '3'
services:
    web:
        image: nginx:alpine
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./web:/var/www/html"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "80:80"
            - "443:443"
        environment:
            - NGINX_HOST=wordpress.local
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - db
            - ftp
    php:
        image: nanoninja/php-fpm
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./web:/var/www/html"
    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_ROOT_PASSWORD: wordpressqwe123
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordqwe123
        ports:
            - "3306:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    ftp:
        image: stilliard/pure-ftpd:hardened
        container_name: pure-ftpd
        restart: always
        environment:
            PUBLICHOST: "ftp"
            FTP_USER_NAME: "wordpressus"
            FTP_USER_PASS: "foobarqux"
            FTP_USER_HOME: "/var/www/html"
        volumes:
            - "./web/public:/var/www/html"
        ports:
            - "21:21"
            - "20:20"
            - "30000-30009:30000-30009"
    ssh:
        image: sashokc/sshsrv
        container_name: sshsrv
        restart: always
        volumes:
            - "./web/public:/var/www/html"
        ports:
            - "333:22"
